[tools]
android-sdk = "latest"
"github:Genymobile/scrcpy" = "4.0"
"github:cesarferreira/byedroid" = "0.9.0"
gradle = "9.6.1"
java = "26.0.1"

[env]
_.path = {tools = true, path = [
 "${ANDROID_HOME}/platform-tools",
 "${ANDROID_HOME}/build-tools/36.0.0",
]}
CPM_SOURCE_CACHE = "${HOME}/.cache/cpm-source-cache"

[settings]
env_shell_expand = true

[tasks.accept-android-licenses]
sources = ['settings.gradle.kts']
run = """
  yes | sdkmanager --licenses
  yes | sdkmanager "cmake;4.1.2"
"""

[tasks.debug-apk]
depends = ["accept-android-licenses"]
sources = [
  'build.gradle.kts',
  'gradle.properties',
  'src/**',
  'settings.gradle.kts',
  'android-sdk-packages.txt'
]
run = "gradle assembleDebug"
alias = "apk"

[tasks.debug-native]
sources = [
  'src/**',
  '*.txt'
]
run = """
  mkdir -p build
  cd build
  cmake ..
  make
"""

[tasks.run-native]
depends = ['debug-native']
run = '''
  ./build/raytris
'''
alias = 'd'
