[tools]
android-sdk = "latest"
"github:Genymobile/scrcpy" = "4.0"
"github:cesarferreira/byedroid" = "0.9.0"
gradle = "9.6.1"
java = "26.0.1"


[env]
_.path = {tools = true, path = [
 "${ANDROID_HOME}/platform-tools",
 "${ANDROID_HOME}/build-tools/36.0.0",
]}

[settings]
env_shell_expand = true

[tasks.accept-android-licenses]
sources = ['settings.gradle.kts']
run = """
  yes | sdkmanager --licenses
"""

[tasks.debug-apk]
depends = ["accept-android-licenses"]
sources = [
  'build.gradle.kts',
  'gradle.properties',
  'src/**',
  'settings.gradle.kts',
  'android-sdk-packages.txt'
]
run = "gradle assembleDebug"
alias = "apk"
