[tools]
android-sdk = "latest"
"github:Genymobile/scrcpy" = "4.0"
"github:cesarferreira/byedroid" = "0.9.0"
gradle = "9.6.1"
java = "26.0.1"
zig = "0.15.1"

[env]
_.path = {tools = true, path = [
 "${ANDROID_HOME}/platform-tools",
 "${ANDROID_HOME}/build-tools/36.0.0",
]}
CPM_SOURCE_CACHE = "${HOME}/.cache/cpm-source-cache"

[settings]
env_shell_expand = true

[tasks.accept-android-licenses]
sources = ['settings.gradle.kts']
run = """
  yes | sdkmanager --licenses
  yes | sdkmanager "cmake;4.1.2"
  yes | sdkmanager "platform-tools"
"""

[tasks.debug-apk]
depends = ["accept-android-licenses"]
sources = [
  'build.gradle.kts',
  'gradle.properties',
  'src/**',
  'settings.gradle.kts',
  'android-sdk-packages.txt',
  'CMakeLists.txt'
]
run = "gradle assembleDebug"
alias = "apk"

[tasks.debug-native]
sources = [
  'src/**/*',
  '*.txt'
]
run = """
  mkdir -p build/debug
  cd build/debug
  cmake ../..
  make
"""

[tasks.debug]
depends = ['debug-native']
run = '''
  ./build/debug/raytris
'''
alias = 'debug'

[tasks.build-windows]
sources = [
  'src/**',
  '*.txt'
]
run = '''
  mkdir -p build/windows
  cd build/windows
  cmake -DCMAKE_TOOLCHAIN_FILE=cmake/zig-toolchain.cmake \
   -DZIG_TARGET=x86_64-windows \
   ../..
  make
'''
